set encoding=utf-8

syntax enable
set background=light

setlocal spell spelllang=en_us
set nospell
set complete+=kspell

set hlsearch

"bash like file auto-complete
set wildmode=longest,list,full
set wildmenu

"vim backup files are more trouble then their worth
set nowritebackup
set noswapfile
set nobackup

set colorcolumn=80
hi ColorColumn ctermbg=grey guibg=grey

""""""""""""""""""""""""""""""""""""""""""""""""
" indentation
"
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

"expose tabs
set list
set listchars=tab:\☞\ 

""""""""""""""""""""""""""""""""""""""""""""""""
" file types
"
autocmd BufNewFile,BufReadPost *.cljx setfiletype clojure
autocmd BufNewFile,BufReadPost *.ecmaless setfiletype python
autocmd BufNewFile,BufReadPost *.ts setfiletype javascript
autocmd BufNewFile,BufReadPost *.md setfiletype markdown
autocmd BufRead,BufNewFile *.md setlocal spell spelllang=en_us

""""""""""""""""""""""""""""""""""""""""""""""""
" key maps
"
let mapleader = ","
let g:mapleader = ","

map <C-s> <esc>:w<CR>
imap <C-s> <esc>:w<CR>

"system copy-paste
map <C-p> :r!xclip -o<CR>
vmap <C-c> :w !xclip -i -selection clipboard<CR><CR>

"toggle line numbers
nnoremap <C-n> :set number!<CR>

"fix common typo's
noremap ; :
command! Q q
command! Qall qall


"stamping
nnoremap S "_diwP

"lambda λ
imap <C-\> <C-K>l*

"function
imap <C-f> function(

"windows
nnoremap <leader>v <C-w>v<C-w>l
nnoremap <leader>s <C-w>s
nnoremap <leader>vsa :vert sba<cr>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


" need to `npm i -g typescript-formatter`
function! FormatTypeScript()
    " save cursor position, folds and many other things (thanks elmcast/elm-vim)
    let l:curw = {}
    try
      mkview!
    catch
      let l:curw = winsaveview()
    endtry

    execute "1,$!tsfmt --stdin"

    " restore our cursor/windows positions, folds, etc.. (thanks elmcast/elm-vim)
    if empty(l:curw)
      silent! loadview
    else
      call winrestview(l:curw)
    endif
endf
"command -buffer FormatTypeScript call FormatTypeScript()
"autocmd BufWritePre *.ts :1,$!tsfmt --stdin
autocmd BufWritePre *.ts call FormatTypeScript()

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" plugins using https://github.com/junegunn/vim-plug
"
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'guns/vim-sexp'
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'kynetx/krl-vim-plugin'

" Show diffs
Plug 'mhinz/vim-signify'

Plug 'elmcast/elm-vim'
let g:elm_format_autosave = 1

Plug 'leafgarland/typescript-vim'
let g:typescript_indent_disable = 1

call plug#end()
